/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentovendas;
import ConexaoBD.ConectaBanco;
import PreenchimentoTabelas.ModeloTabela;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author hugo
 */
public class Tela_Atualizacao extends javax.swing.JFrame {
ConectaBanco conecta = new ConectaBanco();
    /**
     * Creates new form Tela_Atualizacao
     */
    public Tela_Atualizacao() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_cod_consulta = new javax.swing.JTextField();
        jButton_consulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_atualizacao = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_descricao = new javax.swing.JTextField();
        jTextField_quantidade = new javax.swing.JTextField();
        jTextField_quantidade_min = new javax.swing.JTextField();
        jTextField_valor_compra = new javax.swing.JTextField();
        jTextField_valor_venda = new javax.swing.JTextField();
        jButton_atualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botao_voltaEstoque = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel8.setText("jLabel8");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código:");

        jButton_consulta.setText("Buscar");
        jButton_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultaActionPerformed(evt);
            }
        });

        jTable_atualizacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_atualizacao);

        jLabel3.setText("Descrição:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("QuantidadeMIN:");

        jLabel6.setText("Valor Compra:");

        jLabel7.setText("Valor Venda:");

        jTextField_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descricaoActionPerformed(evt);
            }
        });

        jTextField_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_quantidadeActionPerformed(evt);
            }
        });

        jButton_atualizar.setText("Atualizar");
        jButton_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Atualização de Produtos ");

        botao_voltaEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Knob Snapback_1.png"))); // NOI18N
        botao_voltaEstoque.setToolTipText("Voltar");
        botao_voltaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltaEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(jTextField_quantidade)
                                            .addComponent(jTextField_quantidade_min)
                                            .addComponent(jTextField_valor_compra)
                                            .addComponent(jTextField_valor_venda))
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton_atualizar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_cod_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_consulta))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botao_voltaEstoque)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botao_voltaEstoque)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cod_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_consulta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_quantidade_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_valor_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_atualizar))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_quantidadeActionPerformed

    private void botao_voltaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltaEstoqueActionPerformed
        // TODO add your handling code here:
        Tela_estoque telaE = new Tela_estoque();
        telaE.setLocationRelativeTo(null);
        telaE.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_voltaEstoqueActionPerformed

    private void jButton_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultaActionPerformed
      
        int campoConsulta = Integer.parseInt(jTextField_cod_consulta.getText());
        PreencherTabela("select * from produto where id_produto='"+campoConsulta+"'");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_consultaActionPerformed

    private void jTextField_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descricaoActionPerformed

    private void jButton_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizarActionPerformed
            int campo7 = Integer.parseInt(jTextField_cod_consulta.getText()); //passagem dos parametros
            String campo1 = (jTextField_descricao.getText());
            int campo2 = Integer.parseInt(jTextField_quantidade.getText());
            int campo3 = Integer.parseInt(jTextField_quantidade_min.getText());
            double campo4 = Double.parseDouble(jTextField_valor_compra.getText());
            double campo5 = Double.parseDouble(jTextField_valor_venda.getText());
            
    try {
        double campo6 = campo5 - campo4;
        PreparedStatement pst = conecta.conn.prepareStatement("update produto set descricao= ?, quantidade= ?, quantidade_min= ?, preco_compra= ?, preco_venda= ?,lucro_produto= ? where id_produto=?");
       
            pst.setString(1,campo1);   
            pst.setInt(2, campo2);  
            pst.setInt(3,campo3); 
            pst.setDouble(4, campo4);
            pst.setDouble(5, campo5);        
            pst.setInt(7, campo7);
            pst.setDouble(6, campo6);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
        // TODO add your handling code here:
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
    }
        jTextField_cod_consulta.setText("");
        jTextField_descricao.setText("");
        jTextField_quantidade.setText("");
        jTextField_quantidade_min.setText("");
        jTextField_valor_compra.setText("");
        jTextField_valor_venda.setText("");
    
    }//GEN-LAST:event_jButton_atualizarActionPerformed

     public void PreencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String [] Colunas = new String[]{"Codigo","Descrição","Quantidade","QuantidadeMin","Valor Compra","Valor venda"};
    
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
         do{
             dados.add(new Object[]{conecta.rs.getInt("id_produto"),conecta.rs.getString("descricao"),conecta.rs.getInt("quantidade"),conecta.rs.getInt("quantidade_min"),conecta.rs.getDouble("preco_compra"),conecta.rs.getDouble("preco_venda")});
             
           }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erro ao preencher"+ ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTable_atualizacao.setModel(modelo);
        jTable_atualizacao.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTable_atualizacao.getColumnModel().getColumn(0).setResizable(false);
        jTable_atualizacao.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTable_atualizacao.getColumnModel().getColumn(1).setResizable(false);
        jTable_atualizacao.getColumnModel().getColumn(2).setPreferredWidth(75);
        jTable_atualizacao.getColumnModel().getColumn(2).setResizable(false);
        jTable_atualizacao.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_atualizacao.getColumnModel().getColumn(3).setResizable(false);
        jTable_atualizacao.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable_atualizacao.getColumnModel().getColumn(4).setResizable(false);
        jTable_atualizacao.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTable_atualizacao.getColumnModel().getColumn(5).setResizable(false);
        
        jTable_atualizacao.getTableHeader().setReorderingAllowed(false);
        jTable_atualizacao.setAutoResizeMode(jTable_atualizacao.AUTO_RESIZE_OFF);
        jTable_atualizacao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Atualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_voltaEstoque;
    private javax.swing.JButton jButton_atualizar;
    private javax.swing.JButton jButton_consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_atualizacao;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField_cod_consulta;
    private javax.swing.JTextField jTextField_descricao;
    private javax.swing.JTextField jTextField_quantidade;
    private javax.swing.JTextField jTextField_quantidade_min;
    private javax.swing.JTextField jTextField_valor_compra;
    private javax.swing.JTextField jTextField_valor_venda;
    // End of variables declaration//GEN-END:variables
}
